# Generated by Django 4.1.4 on 2023-07-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('recommendation', models.CharField(max_length=50, null=True)),
                ('other', models.CharField(max_length=50, null=True)),
                ('imgpath', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
