# Generated by Django 4.1.4 on 2023-07-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationitem',
            name='imgpath',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notificationitem',
            name='other',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notificationitem',
            name='recommendation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notificationitem',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
