# Generated by Django 4.1.4 on 2022-12-27 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='video_file',
            new_name='movie_file',
        ),
    ]
