# Generated by Django 4.1.4 on 2023-07-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('keepwatching', 'keepwatching'), ('popularatpresent', 'popularatpresent'), ('watchagain', 'watchagain'), ('mylist', 'mylist'), ('any', 'any')], default='any', max_length=50),
        ),
    ]
