# Generated by Django 4.1.4 on 2023-07-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_moviename'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='screenshots/'),
        ),
    ]
