# Generated by Django 4.1.4 on 2023-07-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_movie_screenshot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='moviename',
            new_name='search_terms',
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
