# Generated by Django 4.1.4 on 2023-07-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_movie_category_german'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_time',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
