# Generated by Django 4.1.4 on 2023-08-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_movie_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='special_category_mylist',
            field=models.CharField(choices=[('any', 'any'), ('mylist', 'mylist')], default='any', max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('keepwatching', 'keepwatching'), ('popularatpresent', 'popularatpresent'), ('watchagain', 'watchagain'), ('any', 'any'), ('nature', 'nature'), ('vehicles', 'vehicles'), ('funny', 'funny'), ('animals', 'animals'), ('programming', 'programming'), ('sea', 'sea')], default='any', max_length=50),
        ),
    ]
