# Generated by Django 4.1.4 on 2023-08-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_movie_special_category_mylist_alter_movie_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
    ]
