# Generated by Django 4.1.4 on 2023-08-14 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_movie_is_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='special_category_mylist',
        ),
    ]
