# Generated by Django 4.1.4 on 2023-08-14 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_remove_movie_special_category_mylist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='is_liked',
        ),
    ]
