# Generated by Django 4.1.4 on 2023-08-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_movie_is_liked'),
        ('user', '0004_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_movies',
            field=models.ManyToManyField(to='movies.movie'),
        ),
    ]
