# Generated by Django 4.1.4 on 2023-08-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_remove_movie_special_category_mylist'),
        ('user', '0005_customuser_favorite_movies'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='liked_movies',
            field=models.ManyToManyField(related_name='liked_by_user', to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='favorite_movies',
            field=models.ManyToManyField(related_name='favorited_by_user', to='movies.movie'),
        ),
    ]
