# Generated by Django 4.1.4 on 2023-07-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='Test_user_2023-07-13 08:18:58.389358+00:00', max_length=300, unique=True),
        ),
    ]
