# Generated by Django 4.1.4 on 2022-12-28 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_customuser_is_active_alter_customuser_is_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_name',
        ),
    ]
