# Generated by Django 4.1.4 on 2022-12-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_remove_customuser_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_name',
            field=models.CharField(default=models.EmailField(max_length=254, unique=True, verbose_name='email address'), max_length=300, unique=True),
        ),
    ]
