# Generated by Django 4.1.4 on 2022-12-30 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_customuser_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='user_name',
            new_name='username',
        ),
    ]
